puts "The students of Villains Academy"
puts "---------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michale Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Kreuger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
print "Overall we have "
print 11
puts " great students."